### ISSUE TITLE
Multiformat error

### ISSUE THREAD

**Issue by lillogoal** [dashboardphilippines/react-webcam-barcode-scanner#10]
Error NotFoundException: No MultiFormat Readers were able to detect the code.
    at MultiFormatReader.decodeInternal (http://localhost:4000/static/js/0.chunk.js:199675:11)
    at MultiFormatReader.decodeWithState (http://localhost:4000/static/js/0.chunk.js:199542:17)
    at BrowserMultiFormatReader.decodeBitmap (http://localhost:4000/static/js/0.chunk.js:197284:24)
    at BrowserMultiFormatReader.BrowserCodeReader.decode (http://localhost:4000/static/js/0.chunk.js:196920:17)
    at loop (http://localhost:4000/static/js/0.chunk.js:196856:28)
    at http://localhost:4000/static/js/0.chunk.js:196874:14
    at new Promise (<anonymous>)
    at BrowserMultiFormatReader.BrowserCodeReader.decodeOnce (http://localhost:4000/static/js/0.chunk.js:196873:12)
    at HTMLImageElement._this.imageLoadedListener (http://localhost:4000/static/js/0.chunk.js:196703:22)

**Comment by stajfar** [comment]
I have the same issue with the new version

**Comment by parthsunilmodi** [comment]
I've the same issue

**Comment by umairesketcher** [comment]
I've the same issue ... version : "^0.0.2-rc2"
